apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  name: gstore-git-subscription
  namespace: gstore-git-subscription-ns
  labels:
    mcmapp: gstore-git
spec:
  channel: gstore-git-channel-ns/gstore-git-channel
  name: repo/gstoresales
  placement:
    placementRef: 
      name: gstore-git-placementrule
      kind: PlacementRule
      apiVersion: app.ibm.com/v1alpha1
  overrides:
    - clusterName: "/"
      clusterOverrides:
      - path: "metadata.namespace"
        value: gstore-git-app-ns